sudo: required
services:
  - docker

before_install:
  - docker build -t arijit/docker-react -f Dockerfile.dev .

script:
  - docker run arijit/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: docker-react
 env: DockerReact-env
 bucket_name: "elasticbeanstalk-us-east-2-245114077316"
 bucket_path: "docker-react"
 
on:
  branch: master
access_key_id: "$AWS_ACCESS_KEY"
secret_access_key:
 secure: "$AWS_SECRET_KEY"
